#!/usr/bin/env bash
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$HERE/../final_submit_version/outputs"
DST="$HERE/figures"
mkdir -p "$DST"
cp "$SRC/pipeline_runs/figures/fig6_I5.png"          "$DST/fig6_I5.png"
cp "$SRC/pipeline_runs/figures/fig6_I20.png"         "$DST/fig6_I20.png"
cp "$SRC/pipeline_runs/figures/fig6_I60.png"         "$DST/fig6_I60.png"
cp "$SRC/pipeline_runs/figures/fig7_simple_I5.png"   "$DST/fig7_I5.png"
cp "$SRC/pipeline_runs/figures/fig7_simple_I20.png"  "$DST/fig7_I20.png"
cp "$SRC/pipeline_runs/figures/fig7_simple_I60.png"  "$DST/fig7_I60.png"
cp "$SRC/ppt_images/ppt15_cumulative_returns_L5.png"        "$DST/cum_ret_net_L5.png"
cp "$SRC/ppt_images/ppt15_cumulative_returns_L20.png"       "$DST/cum_ret_net_L20.png"
cp "$SRC/ppt_images/ppt15_cumulative_returns_L60.png"       "$DST/cum_ret_net_L60.png"
cp "$SRC/ppt_images/ppt15_cumulative_returns_gross_L5.png"  "$DST/cum_ret_gross_L5.png"
cp "$SRC/ppt_images/ppt15_cumulative_returns_gross_L20.png" "$DST/cum_ret_gross_L20.png"
cp "$SRC/ppt_images/ppt15_cumulative_returns_gross_L60.png" "$DST/cum_ret_gross_L60.png"
cp "$SRC/pipeline_runs/figures/figure5_vol_adjusted_cumlog.png" "$DST/figure5_vol_adjusted_cumlog.png"
cp "$SRC/pipeline_runs/figures/figure5_vol_adjusted_cumlog_net.png" "$DST/figure5_vol_adjusted_cumlog_net.png"
echo "Staged $(ls "$DST" | wc -l) figure files into $DST"
